"""
Persistent FAISS vector store for the EDA RAG subsystem.

The vector store uses:
    FAISS IndexIDMap2
            +
       IndexFlatIP

Embeddings generated by:
    sentence-transformers/all-mpnet-base-v2

are L2-normalized before being stored.

Therefore:
    Inner Product == Cosine Similarity

Persistent files:
    src/RAG/vector_db/
        eda_rag.index
        eda_rag_metadata.json
"""
from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any

import faiss
import numpy as np

from src.EDA_RAG.config import (
    EMBEDDING_MODEL,
    EMBEDDING_NORMALIZE,
    FAISS_INDEX_NAME,
    METADATA_FILE_NAME,
    RAG_LOG_DIR,
    RAG_VECTOR_DB_DIR,
)
from src.EDA_RAG.schemas.chunk_schema import EDAChunk
from src.EDA_RAG.schemas.retrieval_schema import RetrievalResult
from src.Utils.exception_handler import CustomException
from src.Utils.logger_setup import get_log, track_performance


class FAISSVectorStore:
    """
    Persistent FAISS vector store for EDA chunks.

    Parameters
    ----------
    vector_db_dir:
        Directory used to persist the FAISS index and metadata.
    embedding_model:
        Embedding model used to create the vectors.
    normalize_embeddings:
        Whether embeddings are L2-normalized.

    Notes
    -----
    FAISS stores vectors only. The corresponding EDAChunk
    information is stored separately in JSON metadata.

    Explicit FAISS IDs are used so vector IDs remain stable
    independently of metadata ordering.
    """

    INDEX_VERSION: int = 1

    def __init__(
        self,
        vector_db_dir: Path = RAG_VECTOR_DB_DIR,
        embedding_model: str = EMBEDDING_MODEL,
        normalize_embeddings: bool = EMBEDDING_NORMALIZE,
    ) -> None:
        """Initialize the FAISS vector store."""
        if not embedding_model.strip():
            raise ValueError("embedding_model cannot be empty.")

        self.vector_db_dir = Path(vector_db_dir)
        self.index_path = self.vector_db_dir / FAISS_INDEX_NAME
        self.metadata_path = self.vector_db_dir / METADATA_FILE_NAME
        self.embedding_model = embedding_model
        self.normalize_embeddings = normalize_embeddings

        self.index: faiss.IndexIDMap2 | None = None
        self.embedding_dimension: int | None = None
        self.records: dict[int, EDAChunk] = {}
        self._next_vector_id: int = 0

        self.vector_db_dir.mkdir(parents=True, exist_ok=True)
        self.logger = get_log("FAISSVectorStore", log_dir=RAG_LOG_DIR)
        self.logger.info(
            "FAISS vector store initialized: directory=%s | model=%s",
            self.vector_db_dir,
            self.embedding_model,
        )

    # ADD
    @track_performance
    def add(self, chunks: list[EDAChunk], embeddings: np.ndarray) -> None:
        """
        Add EDA chunks and embeddings to the FAISS index.

        Parameters
        ----------
        chunks:
            EDA chunks corresponding to the embedding rows.
        embeddings:
            Two-dimensional float32 embedding matrix.

        Raises
        ------
        ValueError
            If embeddings or chunks are invalid.
        """
        try:
            if not chunks:
                self.logger.warning("No chunks supplied to FAISS store.")
                return

            embeddings = self._validate_embeddings(embeddings, len(chunks))
            self._initialize_index(embeddings.shape[1])
            assert self.index is not None

            existing_chunk_ids = {chunk.chunk_id for chunk in self.records.values()}
            new_chunks: list[EDAChunk] = []
            new_vectors: list[np.ndarray] = []
            new_ids: list[int] = []

            for index, chunk in enumerate(chunks):
                if chunk.chunk_id in existing_chunk_ids:
                    self.logger.warning("Skipping duplicate chunk: %s", chunk.chunk_id)
                    continue
                vector_id = self._next_vector_id
                self._next_vector_id += 1
                new_chunks.append(chunk)
                new_vectors.append(embeddings[index])
                new_ids.append(vector_id)
                existing_chunk_ids.add(chunk.chunk_id)

            if not new_chunks:
                self.logger.warning("No new chunks to add.")
                return

            vectors = np.vstack(new_vectors).astype(np.float32)
            ids = np.asarray(new_ids, dtype=np.int64)
            self.index.add_with_ids(vectors, ids)

            for vector_id, chunk in zip(new_ids, new_chunks):
                self.records[vector_id] = chunk

            self.logger.info("Added %d chunks. Total vectors=%d.", len(new_chunks), self.count)
        except Exception as exc:
            self.logger.error("Failed to add chunks to FAISS: %s", exc)
            raise CustomException(exc, self.logger) from exc

    # SEARCH
    @track_performance
    def search(
        self,
        query_embedding: np.ndarray,
        top_k: int,
        dataset_id: str | None = None,
        analysis_type: str | None = None,
    ) -> list[RetrievalResult]:
        """
        Search the FAISS index.

        Parameters
        ----------
        query_embedding:
            One-dimensional query embedding.
        top_k:
            Maximum number of results.
        dataset_id:
            Optional dataset filter.
        analysis_type:
            Optional EDA analysis-type filter.

        Returns
        -------
        list[RetrievalResult]
            Results ordered by descending similarity.
        """
        try:
            if top_k <= 0:
                raise ValueError("top_k must be greater than zero.")
            if self.index is None:
                self.logger.warning("FAISS index is not initialized.")
                return []
            if self.count == 0:
                self.logger.warning("FAISS index contains no vectors.")
                return []

            query = self._validate_query_embedding(query_embedding)
            # Request more candidates when filtering because some top results may be filtered out.
            search_k = self.count
            scores, ids = self.index.search(query.reshape(1, -1), search_k)

            results: list[RetrievalResult] = []
            for vector_id, score in zip(ids[0], scores[0]):
                if vector_id == -1:
                    continue
                vector_id = int(vector_id)
                chunk = self.records.get(vector_id)
                if chunk is None:
                    self.logger.warning("No metadata found for vector ID=%d.", vector_id)
                    continue
                if dataset_id is not None and chunk.dataset_id != dataset_id:
                    continue
                if analysis_type is not None and chunk.analysis_type != analysis_type:
                    continue

                results.append(
                    RetrievalResult(
                        chunk_id=chunk.chunk_id,
                        content=chunk.content,
                        score=float(score),
                        rank=len(results) + 1,
                        metadata={
                            **chunk.metadata,
                            "vector_id": vector_id,
                            "document_id": chunk.document_id,
                            "dataset_id": chunk.dataset_id,
                            "analysis_type": chunk.analysis_type,
                            "chunk_index": chunk.chunk_index,
                        },
                    )
                )
                if len(results) >= top_k:
                    break
            return results
        except Exception as exc:
            self.logger.error("FAISS search failed: %s", exc)
            raise CustomException(exc, self.logger) from exc

    # SAVE
    @track_performance
    def save(self) -> None:
        """
        Persist the FAISS index and metadata to disk.
        """
        try:
            if self.index is None:
                raise ValueError("Cannot save an uninitialized FAISS index.")
            self.vector_db_dir.mkdir(parents=True, exist_ok=True)
            self._save_index()
            self._save_metadata()
            self.logger.info(
                "FAISS store saved successfully: vectors=%d | dimension=%s",
                self.count,
                self.embedding_dimension,
            )
        except Exception as exc:
            self.logger.error("Failed to save FAISS store: %s", exc)
            raise CustomException(exc, self.logger) from exc

    # LOAD
    @track_performance
    def load(self) -> None:
        """
        Load the FAISS index and metadata from disk.

        The stored embedding model, normalization configuration,
        dimension, and vector count are validated.
        """
        try:
            if not self.index_path.exists():
                raise FileNotFoundError(f"FAISS index not found: {self.index_path}")
            if not self.metadata_path.exists():
                raise FileNotFoundError(f"FAISS metadata not found: {self.metadata_path}")

            loaded_index = faiss.read_index(str(self.index_path))
            metadata = self._read_metadata()
            self._validate_loaded_store(loaded_index, metadata)

            self.index = loaded_index
            self.embedding_dimension = int(metadata["embedding_dimension"])
            self.records = self._deserialize_records(metadata["records"])
            self._next_vector_id = int(metadata["next_vector_id"])

            self.logger.info(
                "FAISS store loaded: vectors=%d | dimension=%d",
                self.count,
                self.embedding_dimension,
            )
        except Exception as exc:
            self.logger.error("Failed to load FAISS store: %s", exc)
            raise CustomException(exc, self.logger) from exc

    # CLEAR
    @track_performance
    def clear(self) -> None:
        """
        Clear the in-memory store and delete persisted files.
        """
        try:
            self.index = None
            self.embedding_dimension = None
            self.records.clear()
            self._next_vector_id = 0
            if self.index_path.exists():
                self.index_path.unlink()
            if self.metadata_path.exists():
                self.metadata_path.unlink()
            self.logger.info("FAISS vector store cleared.")
        except Exception as exc:
            self.logger.error("Failed to clear FAISS store: %s", exc)
            raise CustomException(exc, self.logger) from exc

    # INITIALIZATION
    def _initialize_index(self, dimension: int) -> None:
        """
        Initialize FAISS IndexIDMap2 over IndexFlatIP.
        """
        if dimension <= 0:
            raise ValueError("Embedding dimension must be greater than zero.")
        if self.index is not None:
            if self.embedding_dimension != dimension:
                raise ValueError(
                    f"Embedding dimension mismatch: existing={self.embedding_dimension}, "
                    f"received={dimension}."
                )
            return

        base_index = faiss.IndexFlatIP(dimension)
        self.index = faiss.IndexIDMap2(base_index)
        self.embedding_dimension = dimension
        self.logger.info(
            "Created FAISS IndexIDMap2/IndexFlatIP: dimension=%d", dimension
        )

    # VALIDATION
    @staticmethod
    def _validate_embeddings(embeddings: np.ndarray, expected_rows: int) -> np.ndarray:
        """
        Validate the embedding matrix.
        """
        embeddings = np.asarray(embeddings, dtype=np.float32)
        if embeddings.ndim != 2:
            raise ValueError("Embeddings must be two-dimensional.")
        if embeddings.shape[0] != expected_rows:
            raise ValueError("Embedding count does not match chunk count.")
        if embeddings.shape[1] == 0:
            raise ValueError("Embedding dimension cannot be zero.")
        if not np.isfinite(embeddings).all():
            raise ValueError("Embeddings contain NaN or infinite values.")
        return embeddings

    def _validate_query_embedding(self, query_embedding: np.ndarray) -> np.ndarray:
        """
        Validate and normalize a query embedding.
        """
        query = np.asarray(query_embedding, dtype=np.float32)
        if query.ndim != 1:
            raise ValueError("Query embedding must be one-dimensional.")
        if query.size == 0:
            raise ValueError("Query embedding cannot be empty.")
        if not np.isfinite(query).all():
            raise ValueError("Query embedding contains invalid values.")
        if self.embedding_dimension != query.shape[0]:
            raise ValueError(
                f"Query embedding dimension mismatch: expected={self.embedding_dimension}, "
                f"received={query.shape[0]}."
            )
        if self.normalize_embeddings:
            norm = np.linalg.norm(query)
            if norm == 0:
                raise ValueError("Cannot normalize zero query vector.")
            query = query / norm
        return query.astype(np.float32)

    # METADATA
    def _build_metadata(self) -> dict[str, Any]:
        """
        Build persistent metadata for the vector store.
        """
        records: dict[str, Any] = {}
        for vector_id, chunk in self.records.items():
            records[str(vector_id)] = {
                "chunk_id": chunk.chunk_id,
                "document_id": chunk.document_id,
                "dataset_id": chunk.dataset_id,
                "analysis_type": chunk.analysis_type,
                "content": chunk.content,
                "chunk_index": chunk.chunk_index,
                "metadata": self._json_safe(chunk.metadata),
            }
        return {
            "version": self.INDEX_VERSION,
            "embedding_model": self.embedding_model,
            "embedding_dimension": self.embedding_dimension,
            "normalize_embeddings": self.normalize_embeddings,
            "metric": "inner_product",
            "index_type": "IndexIDMap2(IndexFlatIP)",
            "count": self.count,
            "next_vector_id": self._next_vector_id,
            "records": records,
        }

    @staticmethod
    def _json_safe(value: Any) -> Any:
        """
        Convert arbitrary metadata into JSON-safe values.
        """
        if value is None:
            return None
        if isinstance(value, dict):
            return {str(key): FAISSVectorStore._json_safe(item) for key, item in value.items()}
        if isinstance(value, (list, tuple)):
            return [FAISSVectorStore._json_safe(item) for item in value]
        if isinstance(value, (str, int, float, bool)):
            return value
        return str(value)

    def _read_metadata(self) -> dict[str, Any]:
        """
        Read metadata JSON from disk.
        """
        with self.metadata_path.open("r", encoding="utf-8") as file:
            metadata = json.load(file)
        if not isinstance(metadata, dict):
            raise ValueError("FAISS metadata must be a JSON object.")
        return metadata

    # METADATA VALIDATION
    def _validate_loaded_store(self, index: faiss.Index, metadata: dict[str, Any]) -> None:
        """
        Validate persisted FAISS index and metadata.
        """
        if metadata.get("version") != self.INDEX_VERSION:
            raise ValueError(f"Unsupported FAISS metadata version: {metadata.get('version')}.")

        stored_model = metadata.get("embedding_model")
        if stored_model != self.embedding_model:
            raise ValueError(
                f"Embedding model mismatch: stored={stored_model}, current={self.embedding_model}."
            )

        if metadata.get("normalize_embeddings") != self.normalize_embeddings:
            raise ValueError(
                "Embedding normalization configuration does not match the stored index."
            )

        dimension = metadata.get("embedding_dimension")
        if not isinstance(dimension, int):
            raise ValueError("Invalid embedding dimension.")
        if index.d != dimension:
            raise ValueError(f"FAISS dimension mismatch: index={index.d}, metadata={dimension}.")

        stored_count = metadata.get("count")
        if stored_count != index.ntotal:
            raise ValueError(
                f"FAISS vector count mismatch: index={index.ntotal}, metadata={stored_count}."
            )

        if metadata.get("metric") != "inner_product":
            raise ValueError("Persisted index does not use inner-product similarity.")

    @staticmethod
    def _deserialize_records(records: dict[str, Any]) -> dict[int, EDAChunk]:
        """
        Reconstruct EDAChunk objects from metadata.
        """
        reconstructed: dict[int, EDAChunk] = {}
        for vector_id, data in records.items():
            if not isinstance(data, dict):
                raise ValueError(f"Invalid metadata for vector ID={vector_id}.")
            reconstructed[int(vector_id)] = EDAChunk(
                chunk_id=data["chunk_id"],
                document_id=data["document_id"],
                dataset_id=data["dataset_id"],
                analysis_type=data["analysis_type"],
                content=data["content"],
                chunk_index=int(data.get("chunk_index", 0)),
                metadata=data.get("metadata", {}),
            )
        return reconstructed

    # PERSISTENCE
    def _save_index(self) -> None:
        """
        Persist the FAISS index using a temporary file.
        """
        fd, temporary_path = tempfile.mkstemp(suffix=".index", dir=self.vector_db_dir)
        os.close(fd)
        try:
            faiss.write_index(self.index, temporary_path)
            os.replace(temporary_path, self.index_path)
        finally:
            if os.path.exists(temporary_path):
                os.remove(temporary_path)

    def _save_metadata(self) -> None:
        """
        Persist metadata using a temporary JSON file.
        """
        metadata = self._build_metadata()
        fd, temporary_path = tempfile.mkstemp(suffix=".json", dir=self.vector_db_dir)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as file:
                json.dump(metadata, file, indent=2, ensure_ascii=False)
                file.flush()
                os.fsync(file.fileno())
            os.replace(temporary_path, self.metadata_path)
        finally:
            if os.path.exists(temporary_path):
                os.remove(temporary_path)

    # PROPERTIES
    @property
    def count(self) -> int:
        """Return the number of vectors in FAISS."""
        if self.index is None:
            return 0
        return int(self.index.ntotal)

    @property
    def dimension(self) -> int | None:
        """Return the embedding dimension."""
        return self.embedding_dimension